### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by salisbury-espinosa** [haofengl/DragNoise#10]
![2024-10-03_05-37](https://github.com/user-attachments/assets/e664d33e-4995-4073-8dce-796fbd8a520f)

**Comment by haofengl** [comment]
Sorry, I didn't identify the specific error. But I suspect it might be due to an incorrect sequence of operations.

**Comment by SichengZheng** [comment]
I have the same problem .I was able to run the code smoothly before. Is it possible that the dependency relationship in the environment has changed.

**Comment by xinyu-pu** [comment]
I have the same problem. I suspect the problem with gradio. My solution is to change the version of gradio to 3.50.1 (conda install conda-forge::gradio==3.50.0).

**Comment by xinyu-pu** [comment]
I have the same problem. I suspect the problem with gradio. My solution is to change the version of gradio to 3.50.0 (conda install conda-forge::gradio==3.50.0).
