### ISSUE TITLE
Does this error indicate a missing file?

### ISSUE THREAD

**Issue by kellyvv** [haofengl/DragNoise#3]
(dragnoise) /content/DragNoise# python3 drag_ui.py
╭──────────── Traceback (most recent call last) ─────────────╮│ /content/DragNoise/drag_ui.py:4 in <module>                ││                                                            │
│     1 import os                                            │
│     2 import gradio as gr                                  │
│     3                                                      │
│ ❱   4 from utils.ui_utils import get_points, undo_points   │
│     5 from utils.ui_utils import clear_all, store_img, tra │
│     6 from utils.ui_utils import clear_all_gen, store_img_ │
│     7                                                      │
│                                                            │
│ /content/DragNoise/utils/ui_utils.py:25 in <module>        │
│                                                            │
│    22                                                      │
│    23 from .drag_utils import drag_diffusion_update        │
│    24 from .lora_utils import train_lora                   │
│ ❱  25 from .attn_utils import register_attention_editor_di │
│    26 from .freeu_utils import register_free_upblock2d, re │
│    27                                                      │
│    28                                                      │
╰────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'utils.attn_utils'

**Comment by FireWallDragonDarkFluid** [comment]
You can comment that line out, since in this repo, it does not use those functions
