### ISSUE TITLE
drag_ui.py:46: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.3 will cause issues.

### ISSUE THREAD

**Issue by RICARDOAIYUAN** [haofengl/DragNoise#4]
![issue](https://github.com/haofengl/DragNoise/assets/94746324/9039a10b-7e8b-4156-a7cf-04abe4dcdaad)

**Comment by haofengl** [comment]
关于gradio布局中的scale为0.3似乎只是个警告，不影响运行。截图中错误应该是Diffusion model的路径没有改成你电脑的路径

**Comment by RICARDOAIYUAN** [comment]
请问model 需要自行下载嘛？

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/18/2024 19:31 |
| To | haofengl/DragNoise ***@***.***> |
| Cc | RICARDOAIYUAN ***@***.***>,
Author ***@***.***> |
| Subject | Re: [haofengl/DragNoise] drag_ui.py:46: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.3 will cause issues. (Issue #4) |

关于gradio布局中的scale为0.3似乎只是个警告，不影响运行。截图中错误应该是Diffusion model的路径没有改成你电脑的路径

**Comment by haofengl** [comment]
是的，下载Stable Diffusion1.5.   https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main

**Comment by RICARDOAIYUAN** [comment]
好的，我稍后试一下，多谢

---- Replied Message ----
| From | ***@***.***> |
| Date | 04/18/2024 19:38 |
| To | haofengl/DragNoise ***@***.***> |
| Cc | RICARDOAIYUAN ***@***.***>,
Author ***@***.***> |
| Subject | Re: [haofengl/DragNoise] drag_ui.py:46: GradioDeprecationWarning: 'scale' value should be an integer. Using 0.3 will cause issues. (Issue #4) |

是的，下载Stable Diffusion1.5. https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main
