### ISSUE TITLE
specific size of "1-LPIPS" and "Mean Distance"

### ISSUE THREAD

**Issue by XuanjiaZ** [haofengl/DragNoise#5]
Hello!
"1-LPIPS" and "Mean Distance": What is the specific size of these two indicators? I can't determine exactly in the diagram of the paper

**Comment by haofengl** [comment]
33.4,0.89,DragNoise,
34.2,0.88,DragDiffusion v5,
35.6,0.88,DragDiffusion v4,
58,0.69,DragGAN,
55,0.70,FreeDrag

**Comment by haofengl** [comment]
33.4,0.89,DragNoise,
34.2,0.88,DragDiffusion v5,
35.6,0.88,DragDiffusion v4
