### ISSUE TITLE
The test results are not satisfactory

### ISSUE THREAD

**Issue by yatoubusha** [haofengl/DragNoise#9]
Why is my performance so poor? How to adjust parameters to improve the effect? I am currently using the default parameters on the demo page
![image](https://github.com/user-attachments/assets/10a953ea-3de0-40b5-8c18-8960150b2b08)
![image](https://github.com/user-attachments/assets/aaf76965-f712-4f4c-b0af-268d7c7912f7)
![image](https://github.com/user-attachments/assets/2dccc3d2-d369-4e96-bbc8-babe093a53d5)
![image](https://github.com/user-attachments/assets/00d864cf-34e1-4953-8c10-06906b7e844f)

**Comment by haofengl** [comment]
Longer edits require an increase in the maximum number of iterations.

**Comment by zsf882299** [comment]
hi, @haofengl, I met the same problem, How to adjust parameters to improve the effect? Thank you ~
